<div class="social-tools bottom-space">
	<div class="container">
		<div class="cms-content">	  
            <h4><center>Term & Conditions</center></h4>   
            <p class="para">Study peer, ______________________ ("Studypeer") operates the internet platforms ("platforms") studypeers.dev(“Site”)his platform have been created to provide information about our company and its web platform and mobile application services for education institutions (such education institutions, our “Client(s”) (such services, together with the Site, the “Service(s)”) to our users (“you”, “your”, “users”, “Client”)</p>
            <p class="para">Users can also book lessons on selected topics in the form of webinars (ie seminars held over the World Wide Web) of various types. Studypeer provides these webinars by means of qualified tutors ("tutors") through an interactive online environment. Any contracts concerning webinars shall be concluded solely between Studypeer and the user; A contractual relationship between the user and the tutor is not substantiated.</p>
            <p class="para"><strong>TERMS AND CONDITIONS</strong><p>
            <p class="para">These terms and conditions govern the contractual relationship between Studypeer and the user.</p>
            <ol class="order-list">
                <li>1.	Account Registration & Termination </li>
            </ol>
            <p class="para">a)	You need an account for most activities on our platform. When setting up and maintaining your account, you must provide and continue to provide accurate and complete information, including a valid email address. You have complete responsibility for your account and everything that happens on your account, including for any harm or damage (to us or anyone else) caused by someone using your account without your permission. This means you need to be careful with your password. You may not transfer your account to someone else or use someone else’s account. If you contact us to request access to an account, we will not grant you such access unless you can provide us with the information that we need to prove you are the owner of that account. In the event of the death of a user, the account of that user will be closed.</p>
            <p class="para">b)	You may not share your account login credentials with anyone else. You are responsible for what happens with your account and Studypeer will not intervene in disputes between students or instructors who have shared account login credentials. You must notify us immediately upon learning that someone else may be using your account without your permission (or if you suspect any other breach of security) by contacting us @ _________. We may request some information from you to confirm that you are indeed the owner of your account.</p>
            <p class="para">c)	Students and instructors must be at least 18 years of age to create an account on Studypeer and use the Services. If you are younger than 18 but above the required age for consent to use online services where you live (for example, 13 in the US or 16 in Ireland), you may not set up an account, but we encourage you to invite a parent or guardian to open an account and help you enroll in courses that are appropriate for you. If you are below this age of consent to use online services, you may not create a Studypeer account. If we discover that you have created an account that violates these rules, we will terminate your account. You may be requested to verify your identity before you are authorized to submit a course for publication on Studypeer.</p>
            <p class="para">d)	Studypeer has the right to terminate your account for any reason at our sole discretion without notice to you.</p>
            <ol class="order-list">
                <li>2.	License and Site Access </li>
            </ol>
            <p class="para">a)	Studypeer grants you a limited license to access and make personal use of the Site. You may not download (other than page caching), or modify any portion of it, except with the express written or e-mailed consent of Studypeer. The license to use the Site does not include any resale or commercial use of the Site or its contents; or any derivative use of this Site or its contents; or any use of data mining, robots or similar data gathering and extraction tools or processes. You agree not to store in any form, distribute, transmit, display, reproduce, modify, create derivative works from, sell or otherwise exploit any of the content on this site for any commercial purpose. By using the Site, you warrant to Studypeer that you will not use the Site, or any of the content obtained from the Site, for any purpose that is unlawful or prohibited by these Terms. Studypeer does not grant any license or other authorization to any user of its trademarks, registered trademarks, service marks, or other copyrightable material or other intellectual property, by placing them on this Website. If you violate any of these Terms, your permission to use the Site automatically terminates.</p>
            <p class="para">b)	In consideration of your use of the Site, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the registration form, if applicable, and (b) to maintain and update this information to keep it true, accurate, current and complete. If any information provided by you is untrue, inaccurate, not current or incomplete, Studypeer has the right to terminate your account and refuse any and all current or future use of the Site. You agree not to resell or transfer the Site or use of or access to the Site.</p>
            <ol class="order-list">
                <li>3. Content and Behaviour Rules</li>
            </ol>
            <p class="para">a)	You can only use Studypeer for lawful purposes. You’re responsible for all the content that you post on our platform. You should keep the reviews, questions, posts, courses and other content you upload in line with our Trust & Safety Guidelines and the law, and respect the intellectual property rights of others. We can ban your account for repeated or major offenses. If you think someone is infringing your copyright on our platform, let us know.</p>
            <p class="para">b)	You may not access or use the Services or create an account for unlawful purposes. Your use of the Services and behaviour on our platform must comply with applicable local or national laws or regulations of your country. You are solely responsible for the knowledge of and compliance with such laws and regulations that are applicable to you.</p>
            <p class="para">c)	You may not access our Services if you are from a territory where U.S. businesses are prohibited from engaging in business (such as Cuba, Iran, North Korea, Sudan, or Syria) or if you have been designated a Specially Designated National, Denied Person, or Denied Entity by the U.S. government. Further, you agree not to upload any content or technology (including information on encryption) whose export is specially controlled under the Export Administration Regulations or other applicable regulations.</p>
            <p class="para">d)	If you are a student, the Services enable you to ask questions to the instructors of courses you are enrolled in, and to post reviews of courses. For certain courses, the instructor may invite you to submit content as “homework” or tests. Don’t post or submit anything that is not yours.</p>
            <p class="para">e)	If you are an instructor, you can submit courses for publication on the platform and you can also communicate with the students who have enrolled in your courses. In both cases, you must abide by the law and respect the rights of others: you cannot post any course, question, answer, review or other content that violates applicable local or national laws or regulations of your country. You are solely responsible for any courses, content, and actions you post or take via the platform and Services and their consequences. </p>
            <p class="para">f)	If we are put on notice that your course or content violates the law or the rights of others (for example, if it is established that it violates intellectual property or image rights of others, or is about an illegal activity), if we discover that your content or behaviour violates any applicable laws/rules/regulations/policies, or if we believe your content or behaviour is unlawful, inappropriate, or objectionable (for example if you impersonate someone else), we may remove your content from our platform. </p>
            <p class="para">g)	Studypeer has discretion in enforcing these Terms and our Trust & Safety Guidelines. We may terminate or suspend your permission to use our platform and Services or ban your account at any time, with or without notice, for any or no reason, including for any violation of these Terms, if you fail to pay any fees when due, upon the request of law enforcement or government agencies, for extended periods of inactivity, for unexpected technical issues or problems, or if we suspect that you engage in fraudulent or illegal activities, or for any other reason in our sole discretion. Upon any such termination we may delete your account and content, and we may prevent you from further access to the platforms and use of our Services. Your content may still be available on the platforms even if your account is terminated or suspended. You agree that we will have no liability to you or any third party for termination of your account, removal of your content, or blocking of your access to our platforms and services.</p>
            <ol class="order-list">
                <li>4.	Using Studypeer at Your Own Risk</li>
            </ol>
            <p class="para">a)	Anyone can use Studypeer to create and publish courses and instructors and we enable instructors and students to interact for teaching and learning. Like other platforms where people can post content and interact, some things can go wrong, and you use Studypeer at your own risk.</p>
            <p class="para">b)	Our platform model means we do not review or edit the courses for legal issues, and we are not in a position to determine the legality of course content. We do not exercise any editorial control over the courses that are available on the platform and, as such, do not guarantee in any manner the reliability, validity, accuracy, or truthfulness of the courses. If you enroll in a course, you rely on any information provided by an instructor at your own risk.</p>
            <p class="para">c)	By using the Services, you may be exposed to content that you consider offensive, indecent, or objectionable. Studypeer has no responsibility to keep such content from you and no liability for your access or enrollment in any course, to the extent permissible under applicable law. </p>
            <p class="para">d)	When you interact directly with a student or an instructor, you must be careful about the types of personal information that you share. While we restrict the types of information instructors may request from students, we do not control what students and instructors do with the information they obtain from other users on the platform. You should not share your email or other personal information about you for your safety.</p>
            <p class="para">e)	We do not hire or employ instructors nor are we responsible or liable for any interactions involved between instructors and students. We are not liable for disputes, claims, losses, injuries, or damage of any kind that might arise out of or relate to the conduct of instructors or students.</p>
            <p class="para">f)	The Site may contain or reference links to web sites operated by third party (“Third Party Websites”). These links are provided as a convenience only. Such Third Party Websites are not under the control of Studypeer. Studypeer is not responsible for the content of any Third Party Website or any link contained in a Third Party Website. Studypeer does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Websites, and the inclusion of any link in the Service is not and does not imply an affiliation, sponsorship, endorsement, approval, investigation, verification or monitoring by Studypeer of any information contained in any Third Party Website. In no event will Studypeer be responsible for the information contained in such Third Party Website or for your use of or inability to use such website. Access to any Third Party Website is at your’s own risk, and you acknowledges and understands that linked Third Party Websites may contain terms and privacy policies that are different from those of Studypeer. Studypeer is not responsible for such provisions, and expressly disclaims any liability for them.</p>
            <p class="para">g)	In connection with your use of the Site, you may be made aware of services, products, offers and promotions provided by third parties, and not by Studypeer. If you decide to use Third Party Services, you are responsible for reviewing and understanding the terms and conditions governing any Third Party Services. You agree that the third party, and not Studypeer, is responsible for the performance of the Third Party Services.</p>
            <ol class="order-list">
                <li>5.	Conduct</li>
            </ol>
            <p class="para">a)	By using the Site you agree that you will not do any of the following:</p>
            <ul class="unordered-list">
                <li>•	Restrict or inhibit any other user from using and enjoying the Site; or</li>
                <li>•	Post or transmit any unlawful, fraudulent, libelous, defamatory, obscene, pornographic, profane, threatening, abusive, hateful, offensive, or otherwise objectionable information of any kind, including without limitation any transmissions constituting or encouraging conduct that would constitute a criminal offense, give rise to civil liability, or otherwise violate any local, state/provincial, national or foreign law, including without limitation the U.S. export control laws and regulations, and Canadian equivalents; or</li>
                <li>•	Post or transmit any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities or schemes or other unsolicited commercial communication (except as otherwise expressly permitted by Studypeer) or engage in spamming or flooding; or</li>
                <li>•	Post or transmit any information or software which contains a virus, trojan horse, worm or other harmful component; or</li>
                <li>•	Post, publish, transmit, reproduce, distribute or in any way exploit any information, software or other material obtained through the Site for commercial purposes (other than as expressly permitted by the provider of such information, software or other material); or</li>
                <li>•	Upload, post, publish, transmit, reproduce, or distribute in any way, information, software or other material obtained through the Site which is protected by copyright, or other proprietary right, or derivative works with respect thereto, without obtaining permission of the copyright owner or right holder.</li>
            </ul>
            <p class="para">b)	Studypeer has no obligation to monitor the Site. However, you acknowledge and agree that Studypeer has the right to monitor the Site electronically from time to time and to disclose any information as necessary or appropriate to satisfy any law, regulation or other governmental request, to operate the Service properly, or to protect itself or its subscribers. Studypeer will not intentionally monitor or disclose any private electronic-mail message unless required by law. Studypeer reserves the right to refuse to post or to remove any information or materials, in whole or in part, that, in its sole discretion, are unacceptable, undesirable, inappropriate or in violation of these Terms of Service.</li>
            <ol class="order-list">
                <li>6.	Studypeer’s Rights</li>
            </ol>
            <p class="para">a)	We own the Studypeer platform and Services, including the website, present or future apps and services, and things like our logos, API, code, and content created by our employees. You can’t tamper with those or use them without authorization.</li>
            <p class="para">b)	All right, title, and interest in and to the Studypeer platform and Services, including our website, our existing or future applications, our APIs, databases, and the content our employees or partners or agents or subcontractors submit or provide through our Services (but excluding content provided by instructors and students) are and will remain the exclusive property of Studypeer and its licensors. Our platforms and services are protected by copyright, trademark, and other laws of both the United States and foreign countries. Nothing gives you a right to use the Studypeer name or any of the Studypeer trademarks, logos, domain names, and other distinctive brand features. Any feedback, comments, or suggestions you may provide regarding Studypeer or the Services is entirely voluntary and we will be free to use such feedback, comments, or suggestions as we see fit and without any obligation to you.</p>
            <p class="para">c)	You may not do any of the following while accessing or using the Studypeer platform and Services:</p>
            <ul class="unordered-list">
                <li>•	access, tamper with, or use non-public areas of the platform (including content storage), Studypeer’s computer systems, or the technical delivery systems of Studypeer’s service providers.</li>
                <li>•	disable, interfere with, or try to circumvent any of the features of the platforms related to security or probe, scan, or test the vulnerability of any of our systems.</li>
                <li>•	copy, modify, create a derivative work of, reverse engineer, reverse assemble, or otherwise attempt to discover any source code of or content on the Studypeer platform or Services.</li>
                <li>•	access or search or attempt to access or search our platform by any means (automated or otherwise) other than through our currently available search functionalities that are provided via our website, mobile apps, or API (and only pursuant to those API terms and conditions). You may not scrape, spider, use a robot, or use other automated means of any kind to access the Services.</li>
                <li>•	in any way use the Services to send altered, deceptive, or false source-identifying information (such as sending email communications falsely appearing as Studypeer); or interfere with, or disrupt, (or attempt to do so), the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the platforms or services, or in any other manner interfering with or creating an undue burden on the Services.</li>
            </ul>
            <ol class="order-list">
                <li>7.	Disclaimers</li>
            </ol>
            <p class="para">It may happen that our platform is down, either for planned maintenance or because something goes down with the site. It may happen that one of our instructors is making misleading statements in their course. It may also happen that we encounter security issues. These are just examples. You accept that you will not have any recourse against us in any of these types of cases where things don’t work out right. In legal, more complete language, <strong>the Services and their content are provided on an “as is” and “as available” basis. We (and our affiliates, suppliers, partners, and agents) make no representations or warranties about the suitability, reliability, availability, timeliness, security, lack of errors, or accuracy of the Services or their content, and expressly disclaim any warranties or conditions (express or implied), including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. We (and our affiliates, suppliers, partners, and agents) make no warranty that you will obtain specific results from use of the Services. Your use of the Services (including any content) is entirely at your own risk. Some jurisdictions don’t allow the exclusion of implied warranties, so some of the above exclusions may not apply to you.</strong></p>
            <p class="para">We may decide to cease making available certain features of the Services at any time and for any reason. Under no circumstances will Studypeer or its affiliates, suppliers, partners or agents be held liable for any damages due to such interruptions or lack of availability of such features.</p>
            <p class="para">We are not responsible for delay or failure of our performance of any of the Services caused by events beyond our reasonable control, like an act of war, hostility, or sabotage; natural disaster; electrical, internet, or telecommunication outage; or government restrictions.</p>
            <ol class="order-list">
                <li>8.	Limitation of Liability</li>
            </ol>
            <p class="para">There are risks inherent to using our Services, for example, if you enroll in a health and wellness course like yoga, and you injure yourself. You fully accept these risks and you agree that you will have no recourse to seek damages against even if you suffer loss or damage from using our platform and Services. In legal, more complete language, <strong>we (and our group companies, suppliers, partners, and agents) will not be liable for any indirect, incidental, punitive, or consequential damages (including loss of data, revenue, profits, or business opportunities, or personal injury or death), whether arising in contract, warranty, tort, product liability, or otherwise, and even if we’ve been advised of the possibility of damages in advance. Our liability (and the liability of each of our group companies, suppliers, partners, and agents) to you or any third parties under any circumstance is limited to the greater of one hundred dollars ($100) or the amount you have paid us in the twelve (12) months before the event giving rise to your claims. </strong></p>
            <ol class="order-list">
                <li>9.	Indemnification</li>
            </ol>
            <p class="para">If you behave in a way that gets us in legal trouble, we may exercise legal recourse against you. You agree to indemnify, defend (if we so request), and hold harmless Studypeer, our group companies, and their officers, directors, suppliers, partners, and agents from an against any third-party claims, demands, losses, damages, or expenses (including reasonable attorney fees) arising from (a) the content you post or submit, (b) your use of the Services (c) your violation of these Terms, or (d) your violation of any rights of a third party. Your indemnification obligation will survive the termination of these Terms and your use of the Services.</p>
            <ol class="order-list">
                <li>10.	Legal Actions and Notices</li>
            </ol>
            <p class="para">No action, regardless of form, arising out of or relating to this Agreement may be brought by either party more than one (1) year after the cause of action has accrued, except where this limitation cannot be imposed by law.</p>
            <p class="para">Any notice or other communication to be given hereunder will be in writing and given by registered or certified mail return receipt requested, or email (by us to the email associated with your account or by you to __________).</p>
            <ol class="order-list">
                <li>11.	Relationship Between Us</li>
            </ol>
            <p class="para">You and we agree that no joint venture, partnership, employment, contractor, or agency relationship exists between us.</p>
            <ol class="order-list">
                <li>12.	No Assignment</li>
            </ol>
            <p class="para">You may not assign or transfer these Terms (or the rights and licenses granted under them). For example, if you registered an account as an employee of a company, your account cannot be transferred to another employee. We may assign these Terms (or the rights and licenses granted under them) to another company or person without restriction. Nothing in these Terms confers any right, benefit, or remedy on any third-party person or entity. You agree that your account is non-transferable and that all rights to your account and other rights under these Terms terminate upon your death.</p>
            <ol class="order-list">
                <li>13.	Entire Agreement</li>
            </ol>
            <p class="para">Except as expressly set forth in these Terms, these Terms of Service are a complete statement of the agreement between you and Studypeer, and set forth the entire liability of Studypeer and its Suppliers and your exclusive remedy with respect to your access and use of the Site. In the event of a conflict between these Terms of Service and the Privacy Policy, these Terms of Service shall prevail. The Suppliers, agents, distributors, dealers, and employees of Studypeer are not authorized to make modifications to the Terms, or to make any additional representations, commitments or warranties binding on Studypeer. Any waiver of the terms herein by Studypeer must be in a writing signed by an authorized officer of Studypeer and expressly referencing the applicable provisions of the Terms. If any provision of the Terms is invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.</p>
            <ol class="order-list">
                <li>14.	Governing Law</li>
            </ol>
            <p class="para">The Terms will be governed by ___________ law as applied to agreements entered into and to be performed entirely within ________, without regard to its choice of law or conflicts of law principles that would require application of law of a different jurisdiction, and applicable federal law. The parties hereby consent to the exclusive jurisdiction and venue in the _____________. </p>
            <ol class="order-list">
                <li>15.	Miscellaneous</li>
            </ol>
            <p class="para">Headings are included for convenience only, and shall not be considered in interpreting these Terms. The Terms do not limit any rights that Studypeer may have under trade secret, copyright, patent or other laws. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Site or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
        </div>
    </div>
</div>